### PR TITLE
🧾 Sean - Final proof

### PR DESCRIPTION
**Pull request by seant1**
#72
Proofed whole report
* Fixed typos, wording
* Add short justification for each stakeholder (was in my notes)
* Add draft conclusion (change it if you want)

Other minor things I found but didn't fix:
* No description for Empathy Maps?
* Some typos in Empathy Maps screenshots

### CODE REVIEW

**Comment by seant1** [comment]
Not sure if we want to change the Problem Definition to sentences instead of dot points or something. Just still seems a bit sketchy(?) and since it's pretty much the first thing the marker will read...

**Comment by SanyaDua** [comment]
Hey Sean, I will add the problem definition and objectives to report:)

**Review by SanyaDua — COMMENTED** [review]
Hey Sean I will add the problem definition and objectives to the report:)

**Review by zachartmann — APPROVED** [review]
If you found typos in the diagram leave them with Ash to just quickly touch up since she has the empathy maps on her computer.
Otherwise, all the changes were nice - really didn't even think about the description of the empathy maps. That's probably necessary hey?
Thanks for doing the conclusion too

**Comment by Aiswarya668** [comment]
Sure I'll take a look at fix up the empathy maps later today so we can cover that part. Also thanks for addressing the additions especially the conclusion! 👍

**Review by Aiswarya668 — APPROVED** [review]

**Pull request merged**
