### PR TITLE
✨Big refactor of entire report structure

### PR DESCRIPTION
**Pull request by seant1**
Made formatting, file naming, etc. more consistent/clear. Check if it's what you want. Also integrated the POVs and HWMs into main report (not sure if they were separated for a reason).

### CODE REVIEW

**Comment by seant1** [comment]
gotta get that emoji right

**Comment by seant1** [comment]
The new report structure without the diffs (if you want to check it):
[https://github.com/seant1/Tutorial10_Group-1/blob/develop/Report.md](https://github.com/seant1/Tutorial10_Group-1/blob/develop/Report.md)

I've also done Section 4 (scrum explanation) but I branched off this report structure so just want to confirm the final report structure (whether or not you want to merge this) before creating a PR for my actual content.
[https://github.com/seant1/Tutorial10_Group-1/pull/2/files](https://github.com/seant1/Tutorial10_Group-1/pull/2/files)

**Review by zachartmann — APPROVED** [review]
Think it looks great and is really what it needed. Glad you got to it before I did because I think you would've just been changing what I did to this anyway ahaha.

Should also get this in before my changes, since it's going to be easier to solve conflicts if I'm adding to the structure rather than adding the structure to me

**Comment by Aiswarya668** [comment]
This looks amazing - thanks for filling in the blanks and putting it together I was wondering whether we needed to include the stuff in the report.writing document. I'll have the design thinking paragraph in my the end of today and I can also put the inbound use case diagram as well!

**Review by Aiswarya668 — APPROVED** [review]

**Pull request merged**
